services:
    david63.activesessions.admin.controller:
        class: david63\activesessions\controller\admin_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@pagination'
            - '@user'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
